const data = [
  "Mobile, Tablet",
  "Mobile Accessories",
  "Earphones",
  "Wearable Devices",
  "Phones & Tablet",
  "Health & Beauty",
  "Skin Care",
  "Sun care",
  "Cleansers",
  "Skin Treatments",
  "Eye Treatments",
  "All Moisturiser",
  "Personal Care",
  "Small Caring tools",
  "Hair styling tools",
  "All Shavers & hair removals",
  "All Hair Removals",
  "Trimmer and Shavers",
  "Makeup",
  "Lips",
  "Eyes & Eyebrows",
  "Face",
  "Makeup Brushes ",
  "Nails",
  "Hair Care",
  "Hair Treatments",
  "Styling Products",
  "Shampoo & Conditioner products",
  "Hair Dyes",
  "Bath & Body Care",
  "Body Care",
  "Hands and Feet",
  "Mouth and Tooth",
  "Feminine care",
  "Baby Care",
  "Men Care",
  "Accessories",
  "Hand Watches",
  "All Fragrances",
  "Body Spray",
  "Body Splash(Mist)",
  "Perfumes",
  "Computing",
  "LapTop",
  "Networking",
  "Routers devices",
  "Data Storage",
  "Memory Cards",
  "Hard Drives",
  "Optical Discs",
  "Computer Units",
  "Cables and Adapters",
  "Splitters",
  "Cables",
  "Computer and Laptop Accessories",
  "PC and Laptop Accessories",
  "Keyboard and Mouse",
  "Home Appliances",
  "Big Home Appliances",
  "Washing Machines",
  "Built -in appliances",
  "Air Conditioners",
  "Refrigerators And Freezers",
  "Refrigerators",
  "Freezer",
  "Small Home Appliances",
  "Water Heaters",
  "Fans",
  "Iron",
  "Air Heater",
  "Ventilating Fan",
  "Water Filters",
  "Kitchen Appliances",
  "Breakfast Appliances",
  "Coffee and Espresso Machines",
  "Fryer",
  "Chopping & Cutting Appliances",
  "Mixing Appliances",
  "Specialized Appliances",
  "Televisions",
  "TVs",
  "Tv Sound System",
  "Tv supplies",
  "More",
  "Fitness Supplies",
  "Bikes",
  "Maintenance Tools",
  "Measuring tools",
  "Laser measuring Tools",
  "Safety and PPE",
  "Equipment Electrical",
  "Grinding",
  "Saws",
  "Pressure washers and accessories",
  "Drills and accessories",
  "Tools Accessories",
  "Cracking And Punching Bits",
  "Cutting And Sanding Disk",
  "Hand Maintenance Tools",
  "Hammer",
  "Pliers",
  "screwdrivers and Wrenches",
  "screwdrivers",
  "Wrenches",
  "Building Supplies",
  "Painting Tools",
  "mount tools",
  "Gardening tools",
  "Electricity ",
  "Batteries",
  "Bags",
  "Laptop Bag",
  "Fashion ",
  "Women",
  "Men",
  "Kids",
  "Toys ",
  "Variety Toys",
  "Sea Toys",
  "Baby Products",
  "Musical Toys",
  "Dolls and Moving Toys",
  "Action Toys",
  "Mind ",
  "Stationery",
  "Stationary Supplies",
  "Office Supplies",
  "Office Machines",
  "Stationery Supplies",
  "Staplers And Punchers ",
  "Board Supplies",
  "Board markers",
  "Tapes And Adhesives",
  "Paper Cutters",
  "Stamps and Supplies",
  "Calculators",
  "School Supplies",
  "Writing Supplies",
  "Pens",
  "Pencils",
  "Markers And Highlighters",
  "Pens and Refills",
  "Erasers and Correction Supplies",
  "Paper Products",
  "Geometry Tools",
  "School Geometry Tools ",
  "University Geometry Tools",
  "Drawing and Colours Supplies",
  "Colours",
  "Felt Pens Colors ",
  "Books",
  "Kitchen ",
  "Kitchen Tools",
  "Scale",
  "Cookware ",
  "Food Storage ",
  "Jars and Spice Set",
  "Knives, Forks, Spoons",
  "Drinkware",
  "Glasses Sets",
  "Cup Sets",
  "Coffee and Tea Equipment",
  "Heat Savers",
  "All Mugs",
  "All mugs and bottles",
  "Water Bottles",
  "Kitchen Accessories",
  "Kitchen Organisers",
  "Plastics",
  "Hand Tools And Devices",
  "Dinnerware",
  "Serving Trays",
  "Table Sets",
  "Serves Set",
  "Bakeware",
  "Home",
  "Lantern",
  "Flashlights",
  "Bulbs",
  "Antiques",
  "Bedding",
  "Towels",
  "Bed Scarves",
  "Furniture",
  "Home Care ",
  "Cleaning Supplies",
  "Household Cleaners",
  "Laundry Care",
  "House Tissues",
  "Pest Control",
  "Electronics",
  "Camera ",
  "Camera Accessories",
  "Batteries and chargers",
  "Printers And Scanners",
  "Printers",
  "Surveillance Systems",
  "Security",
  "Car Kits",
  "Audios",
  "Car Accessories",
  "Audio devices",
  "Microphones",
  "Speakers",
  "Landline Phones",
  "Video Gaming",
  "Video Gaming Accessories",
  "Projector",
];

console.log("Data loaded successfully");
console.log("Total categories:", data.length);
